// Code generated by goent-gen. DO NOT EDIT.
//
//go:build !ignore_autogenerated

package models

import "github.com/azhai/goent"

// ------------------------------
// Activity
// ------------------------------

// implement goent.Entity interface GetID for Activity
func (t *Activity) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Activity
func (t *Activity) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Activity) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "user_id", Value: t.UserID},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "group_id", Value: t.GroupID},
		{Key: "activity_type", Value: t.ActivityType},
		{Key: "title", Value: t.Title},
		{Key: "content", Value: t.Content},
		{Key: "target_id", Value: t.TargetID},
		{Key: "target_type", Value: t.TargetType},
	}
}

// ScanDest returns a slice of pointers to Activity fields for database scanning.
func (t *Activity) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UserID,
		&t.RepositoryID,
		&t.GroupID,
		&t.ActivityType,
		&t.Title,
		&t.Content,
		&t.TargetID,
		&t.TargetType,
	}
}

// FetchActivity creates a FetchFunc for Activity.
func FetchActivity() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Activity).ScanDest()
	}
}

// ------------------------------
// Branch
// ------------------------------

// implement goent.Entity interface GetID for Branch
func (t *Branch) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Branch
func (t *Branch) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Branch) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "name", Value: t.Name},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "commit_hash", Value: t.CommitHash},
		{Key: "commit_msg", Value: t.CommitMsg},
	}
}

// ScanDest returns a slice of pointers to Branch fields for database scanning.
func (t *Branch) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Name,
		&t.RepositoryID,
		&t.CommitHash,
		&t.CommitMsg,
	}
}

// FetchBranch creates a FetchFunc for Branch.
func FetchBranch() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Branch).ScanDest()
	}
}

// ------------------------------
// Comment
// ------------------------------

// implement goent.Entity interface GetID for Comment
func (t *Comment) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Comment
func (t *Comment) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Comment) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "body", Value: t.Body},
		{Key: "github_id", Value: t.GitHubID},
		{Key: "issue_id", Value: t.IssueID},
		{Key: "pull_request_id", Value: t.PullRequestID},
		{Key: "task_id", Value: t.TaskID},
		{Key: "author_id", Value: t.AuthorID},
	}
}

// ScanDest returns a slice of pointers to Comment fields for database scanning.
func (t *Comment) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Body,
		&t.GitHubID,
		&t.IssueID,
		&t.PullRequestID,
		&t.TaskID,
		&t.AuthorID,
	}
}

// FetchComment creates a FetchFunc for Comment.
func FetchComment() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Comment).ScanDest()
	}
}

// ------------------------------
// CommitReference
// ------------------------------

// implement goent.Entity interface GetID for CommitReference
func (t *CommitReference) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for CommitReference
func (t *CommitReference) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *CommitReference) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "commit_hash", Value: t.CommitHash},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "target_type", Value: t.TargetType},
		{Key: "target_id", Value: t.TargetID},
		{Key: "action", Value: t.Action},
	}
}

// ScanDest returns a slice of pointers to CommitReference fields for database scanning.
func (t *CommitReference) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.CommitHash,
		&t.RepositoryID,
		&t.TargetType,
		&t.TargetID,
		&t.Action,
	}
}

// FetchCommitReference creates a FetchFunc for CommitReference.
func FetchCommitReference() goent.FetchFunc {
	return func(target any) []any {
		return target.(*CommitReference).ScanDest()
	}
}

// ------------------------------
// Contributor
// ------------------------------

// implement goent.Entity interface GetID for Contributor
func (t *Contributor) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Contributor
func (t *Contributor) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Contributor) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "name", Value: t.Name},
		{Key: "email", Value: t.Email},
		{Key: "avatar", Value: t.Avatar},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "commits_count", Value: t.CommitsCount},
	}
}

// ScanDest returns a slice of pointers to Contributor fields for database scanning.
func (t *Contributor) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Name,
		&t.Email,
		&t.Avatar,
		&t.RepositoryID,
		&t.CommitsCount,
	}
}

// FetchContributor creates a FetchFunc for Contributor.
func FetchContributor() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Contributor).ScanDest()
	}
}

// ------------------------------
// GitCommandLog
// ------------------------------

// implement goent.Entity interface GetID for GitCommandLog
func (t *GitCommandLog) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for GitCommandLog
func (t *GitCommandLog) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *GitCommandLog) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "command", Value: t.Command},
		{Key: "working_dir", Value: t.WorkingDir},
		{Key: "output", Value: t.Output},
		{Key: "status", Value: t.Status},
		{Key: "started_at", Value: t.StartedAt},
		{Key: "finished_at", Value: t.FinishedAt},
		{Key: "duration_ms", Value: t.DurationMs},
		{Key: "exit_code", Value: t.ExitCode},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "error_msg", Value: t.ErrorMsg},
	}
}

// ScanDest returns a slice of pointers to GitCommandLog fields for database scanning.
func (t *GitCommandLog) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.Command,
		&t.WorkingDir,
		&t.Output,
		&t.Status,
		&t.StartedAt,
		&t.FinishedAt,
		&t.DurationMs,
		&t.ExitCode,
		&t.RepositoryID,
		&t.ErrorMsg,
	}
}

// FetchGitCommandLog creates a FetchFunc for GitCommandLog.
func FetchGitCommandLog() goent.FetchFunc {
	return func(target any) []any {
		return target.(*GitCommandLog).ScanDest()
	}
}

// ------------------------------
// Group
// ------------------------------

// implement goent.Entity interface GetID for Group
func (t *Group) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Group
func (t *Group) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Group) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "name", Value: t.Name},
		{Key: "display_name", Value: t.DisplayName},
		{Key: "description", Value: t.Description},
		{Key: "avatar", Value: t.Avatar},
		{Key: "website", Value: t.Website},
		{Key: "location", Value: t.Location},
		{Key: "owner_id", Value: t.OwnerID},
	}
}

// ScanDest returns a slice of pointers to Group fields for database scanning.
func (t *Group) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Name,
		&t.DisplayName,
		&t.Description,
		&t.Avatar,
		&t.Website,
		&t.Location,
		&t.OwnerID,
	}
}

// FetchGroup creates a FetchFunc for Group.
func FetchGroup() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Group).ScanDest()
	}
}

// ------------------------------
// GroupMember
// ------------------------------

// implement goent.Entity interface GetID for GroupMember
func (t *GroupMember) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for GroupMember
func (t *GroupMember) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *GroupMember) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "group_id", Value: t.GroupID},
		{Key: "user_id", Value: t.UserID},
		{Key: "role", Value: t.Role},
	}
}

// ScanDest returns a slice of pointers to GroupMember fields for database scanning.
func (t *GroupMember) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.GroupID,
		&t.UserID,
		&t.Role,
	}
}

// FetchGroupMember creates a FetchFunc for GroupMember.
func FetchGroupMember() goent.FetchFunc {
	return func(target any) []any {
		return target.(*GroupMember).ScanDest()
	}
}

// ------------------------------
// Issue
// ------------------------------

// implement goent.Entity interface GetID for Issue
func (t *Issue) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Issue
func (t *Issue) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Issue) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "title", Value: t.Title},
		{Key: "body", Value: t.Body},
		{Key: "number", Value: t.Number},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "author_id", Value: t.AuthorID},
		{Key: "assignee_id", Value: t.AssigneeID},
		{Key: "is_closed", Value: t.IsClosed},
		{Key: "is_locked", Value: t.IsLocked},
	}
}

// ScanDest returns a slice of pointers to Issue fields for database scanning.
func (t *Issue) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Title,
		&t.Body,
		&t.Number,
		&t.RepositoryID,
		&t.AuthorID,
		&t.AssigneeID,
		&t.IsClosed,
		&t.IsLocked,
	}
}

// FetchIssue creates a FetchFunc for Issue.
func FetchIssue() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Issue).ScanDest()
	}
}

// ------------------------------
// IssueLabel
// ------------------------------

// implement goent.Entity interface GetID for IssueLabel
func (t *IssueLabel) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for IssueLabel
func (t *IssueLabel) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *IssueLabel) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "issue_id", Value: t.IssueID},
		{Key: "label_id", Value: t.LabelID},
		{Key: "created_at", Value: t.CreatedAt},
	}
}

// ScanDest returns a slice of pointers to IssueLabel fields for database scanning.
func (t *IssueLabel) ScanDest() []any {
	return []any{
		&t.ID,
		&t.IssueID,
		&t.LabelID,
		&t.CreatedAt,
	}
}

// FetchIssueLabel creates a FetchFunc for IssueLabel.
func FetchIssueLabel() goent.FetchFunc {
	return func(target any) []any {
		return target.(*IssueLabel).ScanDest()
	}
}

// ------------------------------
// Label
// ------------------------------

// implement goent.Entity interface GetID for Label
func (t *Label) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Label
func (t *Label) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Label) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "name", Value: t.Name},
		{Key: "color", Value: t.Color},
		{Key: "description", Value: t.Description},
		{Key: "repository_id", Value: t.RepositoryID},
	}
}

// ScanDest returns a slice of pointers to Label fields for database scanning.
func (t *Label) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Name,
		&t.Color,
		&t.Description,
		&t.RepositoryID,
	}
}

// FetchLabel creates a FetchFunc for Label.
func FetchLabel() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Label).ScanDest()
	}
}

// ------------------------------
// Milestone
// ------------------------------

// implement goent.Entity interface GetID for Milestone
func (t *Milestone) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Milestone
func (t *Milestone) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Milestone) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "title", Value: t.Title},
		{Key: "description", Value: t.Description},
		{Key: "due_date", Value: t.DueDate},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "is_closed", Value: t.IsClosed},
	}
}

// ScanDest returns a slice of pointers to Milestone fields for database scanning.
func (t *Milestone) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Title,
		&t.Description,
		&t.DueDate,
		&t.RepositoryID,
		&t.IsClosed,
	}
}

// FetchMilestone creates a FetchFunc for Milestone.
func FetchMilestone() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Milestone).ScanDest()
	}
}

// ------------------------------
// Owner
// ------------------------------

// implement goent.Entity interface GetID for Owner
func (t *Owner) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Owner
func (t *Owner) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Owner) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "username", Value: t.Username},
		{Key: "email", Value: t.Email},
		{Key: "full_name", Value: t.FullName},
		{Key: "avatar", Value: t.Avatar},
	}
}

// ScanDest returns a slice of pointers to Owner fields for database scanning.
func (t *Owner) ScanDest() []any {
	return []any{
		&t.ID,
		&t.Username,
		&t.Email,
		&t.FullName,
		&t.Avatar,
	}
}

// FetchOwner creates a FetchFunc for Owner.
func FetchOwner() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Owner).ScanDest()
	}
}

// ------------------------------
// PlatformAccount
// ------------------------------

// implement goent.Entity interface GetID for PlatformAccount
func (t *PlatformAccount) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for PlatformAccount
func (t *PlatformAccount) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *PlatformAccount) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "platform", Value: t.Platform},
		{Key: "username", Value: t.Username},
		{Key: "email", Value: t.Email},
		{Key: "avatar_url", Value: t.AvatarURL},
		{Key: "apiurl", Value: t.APIURL},
		{Key: "is_active", Value: t.IsActive},
		{Key: "user_id", Value: t.UserID},
	}
}

// ScanDest returns a slice of pointers to PlatformAccount fields for database scanning.
func (t *PlatformAccount) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Platform,
		&t.Username,
		&t.Email,
		&t.AvatarURL,
		&t.APIURL,
		&t.IsActive,
		&t.UserID,
	}
}

// FetchPlatformAccount creates a FetchFunc for PlatformAccount.
func FetchPlatformAccount() goent.FetchFunc {
	return func(target any) []any {
		return target.(*PlatformAccount).ScanDest()
	}
}

// ------------------------------
// PullRequest
// ------------------------------

// implement goent.Entity interface GetID for PullRequest
func (t *PullRequest) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for PullRequest
func (t *PullRequest) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *PullRequest) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "title", Value: t.Title},
		{Key: "body", Value: t.Body},
		{Key: "number", Value: t.Number},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "author_id", Value: t.AuthorID},
		{Key: "source_branch", Value: t.SourceBranch},
		{Key: "target_branch", Value: t.TargetBranch},
		{Key: "assignee_id", Value: t.AssigneeID},
		{Key: "status", Value: t.Status},
		{Key: "is_merged", Value: t.IsMerged},
		{Key: "is_closed", Value: t.IsClosed},
		{Key: "is_locked", Value: t.IsLocked},
	}
}

// ScanDest returns a slice of pointers to PullRequest fields for database scanning.
func (t *PullRequest) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Title,
		&t.Body,
		&t.Number,
		&t.RepositoryID,
		&t.AuthorID,
		&t.SourceBranch,
		&t.TargetBranch,
		&t.AssigneeID,
		&t.Status,
		&t.IsMerged,
		&t.IsClosed,
		&t.IsLocked,
	}
}

// FetchPullRequest creates a FetchFunc for PullRequest.
func FetchPullRequest() goent.FetchFunc {
	return func(target any) []any {
		return target.(*PullRequest).ScanDest()
	}
}

// ------------------------------
// PullRequestLabel
// ------------------------------

// implement goent.Entity interface GetID for PullRequestLabel
func (t *PullRequestLabel) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for PullRequestLabel
func (t *PullRequestLabel) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *PullRequestLabel) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "pull_request_id", Value: t.PullRequestID},
		{Key: "label_id", Value: t.LabelID},
		{Key: "created_at", Value: t.CreatedAt},
	}
}

// ScanDest returns a slice of pointers to PullRequestLabel fields for database scanning.
func (t *PullRequestLabel) ScanDest() []any {
	return []any{
		&t.ID,
		&t.PullRequestID,
		&t.LabelID,
		&t.CreatedAt,
	}
}

// FetchPullRequestLabel creates a FetchFunc for PullRequestLabel.
func FetchPullRequestLabel() goent.FetchFunc {
	return func(target any) []any {
		return target.(*PullRequestLabel).ScanDest()
	}
}

// ------------------------------
// Release
// ------------------------------

// implement goent.Entity interface GetID for Release
func (t *Release) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Release
func (t *Release) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Release) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "tag_name", Value: t.TagName},
		{Key: "title", Value: t.Title},
		{Key: "body", Value: t.Body},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "author_id", Value: t.AuthorID},
		{Key: "is_draft", Value: t.IsDraft},
		{Key: "is_prerelease", Value: t.IsPrerelease},
	}
}

// ScanDest returns a slice of pointers to Release fields for database scanning.
func (t *Release) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.TagName,
		&t.Title,
		&t.Body,
		&t.RepositoryID,
		&t.AuthorID,
		&t.IsDraft,
		&t.IsPrerelease,
	}
}

// FetchRelease creates a FetchFunc for Release.
func FetchRelease() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Release).ScanDest()
	}
}

// ------------------------------
// RemoteRepository
// ------------------------------

// implement goent.Entity interface GetID for RemoteRepository
func (t *RemoteRepository) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for RemoteRepository
func (t *RemoteRepository) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *RemoteRepository) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "platform", Value: t.Platform},
		{Key: "owner", Value: t.Owner},
		{Key: "repo_name", Value: t.RepoName},
		{Key: "clone_url", Value: t.CloneURL},
		{Key: "sshurl", Value: t.SSHURL},
		{Key: "apiurl", Value: t.APIURL},
		{Key: "web_url", Value: t.WebURL},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "account_id", Value: t.AccountID},
		{Key: "is_primary", Value: t.IsPrimary},
		{Key: "direction", Value: t.Direction},
		{Key: "last_sync_at", Value: t.LastSyncAt},
		{Key: "sync_enabled", Value: t.SyncEnabled},
	}
}

// ScanDest returns a slice of pointers to RemoteRepository fields for database scanning.
func (t *RemoteRepository) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Platform,
		&t.Owner,
		&t.RepoName,
		&t.CloneURL,
		&t.SSHURL,
		&t.APIURL,
		&t.WebURL,
		&t.RepositoryID,
		&t.AccountID,
		&t.IsPrimary,
		&t.Direction,
		&t.LastSyncAt,
		&t.SyncEnabled,
	}
}

// FetchRemoteRepository creates a FetchFunc for RemoteRepository.
func FetchRemoteRepository() goent.FetchFunc {
	return func(target any) []any {
		return target.(*RemoteRepository).ScanDest()
	}
}

// ------------------------------
// Repository
// ------------------------------

// implement goent.Entity interface GetID for Repository
func (t *Repository) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Repository
func (t *Repository) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Repository) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "name", Value: t.Name},
		{Key: "description", Value: t.Description},
		{Key: "homepage", Value: t.Homepage},
		{Key: "readme", Value: t.Readme},
		{Key: "owner_id", Value: t.OwnerID},
		{Key: "owner_type", Value: t.OwnerType},
		{Key: "project_type", Value: t.ProjectType},
		{Key: "is_fork", Value: t.IsFork},
		{Key: "mirror_url", Value: t.MirrorURL},
		{Key: "last_sync_at", Value: t.LastSyncAt},
		{Key: "local_path", Value: t.LocalPath},
		{Key: "migrate_status", Value: t.MigrateStatus},
		{Key: "migrate_error", Value: t.MigrateError},
		{Key: "default_branch", Value: t.DefaultBranch},
		{Key: "last_commit_at", Value: t.LastCommitAt},
	}
}

// ScanDest returns a slice of pointers to Repository fields for database scanning.
func (t *Repository) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Name,
		&t.Description,
		&t.Homepage,
		&t.Readme,
		&t.OwnerID,
		&t.OwnerType,
		&t.ProjectType,
		&t.IsFork,
		&t.MirrorURL,
		&t.LastSyncAt,
		&t.LocalPath,
		&t.MigrateStatus,
		&t.MigrateError,
		&t.DefaultBranch,
		&t.LastCommitAt,
	}
}

// FetchRepository creates a FetchFunc for Repository.
func FetchRepository() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Repository).ScanDest()
	}
}

// ------------------------------
// RepositoryStats
// ------------------------------

// implement goent.Entity interface GetID for RepositoryStats
func (t *RepositoryStats) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for RepositoryStats
func (t *RepositoryStats) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *RepositoryStats) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "last_commit_at", Value: t.LastCommitAt},
		{Key: "stars_count", Value: t.StarsCount},
		{Key: "forks_count", Value: t.ForksCount},
		{Key: "watch_count", Value: t.WatchCount},
		{Key: "commits_count", Value: t.CommitsCount},
		{Key: "branches_count", Value: t.BranchesCount},
		{Key: "tags_count", Value: t.TagsCount},
		{Key: "contributors_count", Value: t.ContributorsCount},
		{Key: "open_issues_count", Value: t.OpenIssuesCount},
		{Key: "closed_issues_count", Value: t.ClosedIssuesCount},
		{Key: "open_prs_count", Value: t.OpenPRsCount},
		{Key: "closed_prs_count", Value: t.ClosedPRsCount},
	}
}

// ScanDest returns a slice of pointers to RepositoryStats fields for database scanning.
func (t *RepositoryStats) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.RepositoryID,
		&t.LastCommitAt,
		&t.StarsCount,
		&t.ForksCount,
		&t.WatchCount,
		&t.CommitsCount,
		&t.BranchesCount,
		&t.TagsCount,
		&t.ContributorsCount,
		&t.OpenIssuesCount,
		&t.ClosedIssuesCount,
		&t.OpenPRsCount,
		&t.ClosedPRsCount,
	}
}

// FetchRepositoryStats creates a FetchFunc for RepositoryStats.
func FetchRepositoryStats() goent.FetchFunc {
	return func(target any) []any {
		return target.(*RepositoryStats).ScanDest()
	}
}

// ------------------------------
// Snippet
// ------------------------------

// implement goent.Entity interface GetID for Snippet
func (t *Snippet) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Snippet
func (t *Snippet) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Snippet) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "title", Value: t.Title},
		{Key: "description", Value: t.Description},
		{Key: "language", Value: t.Language},
		{Key: "code", Value: t.Code},
		{Key: "visibility", Value: t.Visibility},
		{Key: "version", Value: t.Version},
		{Key: "user_id", Value: t.UserID},
		{Key: "repository_id", Value: t.RepositoryID},
	}
}

// ScanDest returns a slice of pointers to Snippet fields for database scanning.
func (t *Snippet) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Title,
		&t.Description,
		&t.Language,
		&t.Code,
		&t.Visibility,
		&t.Version,
		&t.UserID,
		&t.RepositoryID,
	}
}

// FetchSnippet creates a FetchFunc for Snippet.
func FetchSnippet() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Snippet).ScanDest()
	}
}

// ------------------------------
// Star
// ------------------------------

// implement goent.Entity interface GetID for Star
func (t *Star) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Star
func (t *Star) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Star) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "user_id", Value: t.UserID},
		{Key: "repository_id", Value: t.RepositoryID},
	}
}

// ScanDest returns a slice of pointers to Star fields for database scanning.
func (t *Star) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UserID,
		&t.RepositoryID,
	}
}

// FetchStar creates a FetchFunc for Star.
func FetchStar() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Star).ScanDest()
	}
}

// ------------------------------
// SyncLog
// ------------------------------

// implement goent.Entity interface GetID for SyncLog
func (t *SyncLog) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for SyncLog
func (t *SyncLog) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *SyncLog) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "sync_point_id", Value: t.SyncPointID},
		{Key: "sync_type", Value: t.SyncType},
		{Key: "status", Value: t.Status},
		{Key: "message", Value: t.Message},
		{Key: "duration", Value: t.Duration},
		{Key: "items_synced", Value: t.ItemsSynced},
		{Key: "items_failed", Value: t.ItemsFailed},
		{Key: "details", Value: t.Details},
	}
}

// ScanDest returns a slice of pointers to SyncLog fields for database scanning.
func (t *SyncLog) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.SyncPointID,
		&t.SyncType,
		&t.Status,
		&t.Message,
		&t.Duration,
		&t.ItemsSynced,
		&t.ItemsFailed,
		&t.Details,
	}
}

// FetchSyncLog creates a FetchFunc for SyncLog.
func FetchSyncLog() goent.FetchFunc {
	return func(target any) []any {
		return target.(*SyncLog).ScanDest()
	}
}

// ------------------------------
// SyncPoint
// ------------------------------

// implement goent.Entity interface GetID for SyncPoint
func (t *SyncPoint) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for SyncPoint
func (t *SyncPoint) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *SyncPoint) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "remote_repo_id", Value: t.RemoteRepoID},
		{Key: "sync_type", Value: t.SyncType},
		{Key: "last_sync_at", Value: t.LastSyncAt},
		{Key: "last_success_at", Value: t.LastSuccessAt},
		{Key: "last_failure_at", Value: t.LastFailureAt},
		{Key: "failure_count", Value: t.FailureCount},
		{Key: "last_commit_hash", Value: t.LastCommitHash},
		{Key: "last_issue_number", Value: t.LastIssueNumber},
		{Key: "last_pr_number", Value: t.LastPRNumber},
		{Key: "last_issue_sync_at", Value: t.LastIssueSyncAt},
		{Key: "last_pr_sync_at", Value: t.LastPRSyncAt},
		{Key: "last_e_tag", Value: t.LastETag},
		{Key: "last_modified", Value: t.LastModified},
		{Key: "next_sync_at", Value: t.NextSyncAt},
		{Key: "sync_interval", Value: t.SyncInterval},
		{Key: "last_error", Value: t.LastError},
		{Key: "is_paused", Value: t.IsPaused},
	}
}

// ScanDest returns a slice of pointers to SyncPoint fields for database scanning.
func (t *SyncPoint) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.RepositoryID,
		&t.RemoteRepoID,
		&t.SyncType,
		&t.LastSyncAt,
		&t.LastSuccessAt,
		&t.LastFailureAt,
		&t.FailureCount,
		&t.LastCommitHash,
		&t.LastIssueNumber,
		&t.LastPRNumber,
		&t.LastIssueSyncAt,
		&t.LastPRSyncAt,
		&t.LastETag,
		&t.LastModified,
		&t.NextSyncAt,
		&t.SyncInterval,
		&t.LastError,
		&t.IsPaused,
	}
}

// FetchSyncPoint creates a FetchFunc for SyncPoint.
func FetchSyncPoint() goent.FetchFunc {
	return func(target any) []any {
		return target.(*SyncPoint).ScanDest()
	}
}

// ------------------------------
// SyncToken
// ------------------------------

// implement goent.Entity interface GetID for SyncToken
func (t *SyncToken) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for SyncToken
func (t *SyncToken) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *SyncToken) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "platform", Value: t.Platform},
		{Key: "name", Value: t.Name},
		{Key: "access_token", Value: t.AccessToken},
		{Key: "refresh_token", Value: t.RefreshToken},
		{Key: "token_type", Value: t.TokenType},
		{Key: "expires_at", Value: t.ExpiresAt},
		{Key: "scopes", Value: t.Scopes},
		{Key: "account_id", Value: t.AccountID},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "is_active", Value: t.IsActive},
	}
}

// ScanDest returns a slice of pointers to SyncToken fields for database scanning.
func (t *SyncToken) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Platform,
		&t.Name,
		&t.AccessToken,
		&t.RefreshToken,
		&t.TokenType,
		&t.ExpiresAt,
		&t.Scopes,
		&t.AccountID,
		&t.RepositoryID,
		&t.IsActive,
	}
}

// FetchSyncToken creates a FetchFunc for SyncToken.
func FetchSyncToken() goent.FetchFunc {
	return func(target any) []any {
		return target.(*SyncToken).ScanDest()
	}
}

// ------------------------------
// Task
// ------------------------------

// implement goent.Entity interface GetID for Task
func (t *Task) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Task
func (t *Task) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Task) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "title", Value: t.Title},
		{Key: "draft", Value: t.Draft},
		{Key: "goal", Value: t.Goal},
		{Key: "preview_image", Value: t.PreviewImage},
		{Key: "status", Value: t.Status},
		{Key: "priority", Value: t.Priority},
		{Key: "sort_order", Value: t.SortOrder},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "initiator_id", Value: t.InitiatorID},
		{Key: "verifier_id", Value: t.VerifierID},
		{Key: "handler_id", Value: t.HandlerID},
		{Key: "last_handled_at", Value: t.LastHandledAt},
	}
}

// ScanDest returns a slice of pointers to Task fields for database scanning.
func (t *Task) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Title,
		&t.Draft,
		&t.Goal,
		&t.PreviewImage,
		&t.Status,
		&t.Priority,
		&t.SortOrder,
		&t.RepositoryID,
		&t.InitiatorID,
		&t.VerifierID,
		&t.HandlerID,
		&t.LastHandledAt,
	}
}

// FetchTask creates a FetchFunc for Task.
func FetchTask() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Task).ScanDest()
	}
}

// ------------------------------
// TaskAttachment
// ------------------------------

// implement goent.Entity interface GetID for TaskAttachment
func (t *TaskAttachment) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for TaskAttachment
func (t *TaskAttachment) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *TaskAttachment) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "task_id", Value: t.TaskID},
		{Key: "file_name", Value: t.FileName},
		{Key: "file_path", Value: t.FilePath},
		{Key: "file_size", Value: t.FileSize},
		{Key: "file_type", Value: t.FileType},
	}
}

// ScanDest returns a slice of pointers to TaskAttachment fields for database scanning.
func (t *TaskAttachment) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.TaskID,
		&t.FileName,
		&t.FilePath,
		&t.FileSize,
		&t.FileType,
	}
}

// FetchTaskAttachment creates a FetchFunc for TaskAttachment.
func FetchTaskAttachment() goent.FetchFunc {
	return func(target any) []any {
		return target.(*TaskAttachment).ScanDest()
	}
}

// ------------------------------
// TaskIssue
// ------------------------------

// implement goent.Entity interface GetID for TaskIssue
func (t *TaskIssue) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for TaskIssue
func (t *TaskIssue) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *TaskIssue) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "task_id", Value: t.TaskID},
		{Key: "issue_id", Value: t.IssueID},
	}
}

// ScanDest returns a slice of pointers to TaskIssue fields for database scanning.
func (t *TaskIssue) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.TaskID,
		&t.IssueID,
	}
}

// FetchTaskIssue creates a FetchFunc for TaskIssue.
func FetchTaskIssue() goent.FetchFunc {
	return func(target any) []any {
		return target.(*TaskIssue).ScanDest()
	}
}

// ------------------------------
// TaskPullRequest
// ------------------------------

// implement goent.Entity interface GetID for TaskPullRequest
func (t *TaskPullRequest) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for TaskPullRequest
func (t *TaskPullRequest) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *TaskPullRequest) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "task_id", Value: t.TaskID},
		{Key: "pull_request_id", Value: t.PullRequestID},
	}
}

// ScanDest returns a slice of pointers to TaskPullRequest fields for database scanning.
func (t *TaskPullRequest) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.TaskID,
		&t.PullRequestID,
	}
}

// FetchTaskPullRequest creates a FetchFunc for TaskPullRequest.
func FetchTaskPullRequest() goent.FetchFunc {
	return func(target any) []any {
		return target.(*TaskPullRequest).ScanDest()
	}
}

// ------------------------------
// TaskSchedule
// ------------------------------

// implement goent.Entity interface GetID for TaskSchedule
func (t *TaskSchedule) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for TaskSchedule
func (t *TaskSchedule) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *TaskSchedule) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "task_id", Value: t.TaskID},
		{Key: "schedule_type", Value: t.ScheduleType},
		{Key: "plan_start_date", Value: t.PlanStartDate},
		{Key: "plan_end_date", Value: t.PlanEndDate},
		{Key: "plan_start_noon", Value: t.PlanStartNoon},
		{Key: "plan_end_noon", Value: t.PlanEndNoon},
		{Key: "actual_start_date", Value: t.ActualStartDate},
		{Key: "actual_end_date", Value: t.ActualEndDate},
		{Key: "actual_start_noon", Value: t.ActualStartNoon},
		{Key: "actual_end_noon", Value: t.ActualEndNoon},
		{Key: "user1_id", Value: t.User1ID},
		{Key: "user2_id", Value: t.User2ID},
		{Key: "user3_id", Value: t.User3ID},
	}
}

// ScanDest returns a slice of pointers to TaskSchedule fields for database scanning.
func (t *TaskSchedule) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.TaskID,
		&t.ScheduleType,
		&t.PlanStartDate,
		&t.PlanEndDate,
		&t.PlanStartNoon,
		&t.PlanEndNoon,
		&t.ActualStartDate,
		&t.ActualEndDate,
		&t.ActualStartNoon,
		&t.ActualEndNoon,
		&t.User1ID,
		&t.User2ID,
		&t.User3ID,
	}
}

// FetchTaskSchedule creates a FetchFunc for TaskSchedule.
func FetchTaskSchedule() goent.FetchFunc {
	return func(target any) []any {
		return target.(*TaskSchedule).ScanDest()
	}
}

// ------------------------------
// TaskTimeLog
// ------------------------------

// implement goent.Entity interface GetID for TaskTimeLog
func (t *TaskTimeLog) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for TaskTimeLog
func (t *TaskTimeLog) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *TaskTimeLog) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "task_id", Value: t.TaskID},
		{Key: "user_id", Value: t.UserID},
		{Key: "start_time", Value: t.StartTime},
		{Key: "end_time", Value: t.EndTime},
		{Key: "duration", Value: t.Duration},
		{Key: "note", Value: t.Note},
	}
}

// ScanDest returns a slice of pointers to TaskTimeLog fields for database scanning.
func (t *TaskTimeLog) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.TaskID,
		&t.UserID,
		&t.StartTime,
		&t.EndTime,
		&t.Duration,
		&t.Note,
	}
}

// FetchTaskTimeLog creates a FetchFunc for TaskTimeLog.
func FetchTaskTimeLog() goent.FetchFunc {
	return func(target any) []any {
		return target.(*TaskTimeLog).ScanDest()
	}
}

// ------------------------------
// TaskTransition
// ------------------------------

// implement goent.Entity interface GetID for TaskTransition
func (t *TaskTransition) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for TaskTransition
func (t *TaskTransition) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *TaskTransition) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "task_id", Value: t.TaskID},
		{Key: "from_status", Value: t.FromStatus},
		{Key: "to_status", Value: t.ToStatus},
		{Key: "user_id", Value: t.UserID},
		{Key: "comment", Value: t.Comment},
	}
}

// ScanDest returns a slice of pointers to TaskTransition fields for database scanning.
func (t *TaskTransition) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.TaskID,
		&t.FromStatus,
		&t.ToStatus,
		&t.UserID,
		&t.Comment,
	}
}

// FetchTaskTransition creates a FetchFunc for TaskTransition.
func FetchTaskTransition() goent.FetchFunc {
	return func(target any) []any {
		return target.(*TaskTransition).ScanDest()
	}
}

// ------------------------------
// User
// ------------------------------

// implement goent.Entity interface GetID for User
func (t *User) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for User
func (t *User) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *User) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "username", Value: t.Username},
		{Key: "email", Value: t.Email},
		{Key: "password", Value: t.Password},
		{Key: "full_name", Value: t.FullName},
		{Key: "avatar", Value: t.Avatar},
		{Key: "bio", Value: t.Bio},
		{Key: "website", Value: t.Website},
		{Key: "location", Value: t.Location},
		{Key: "is_active", Value: t.IsActive},
		{Key: "role", Value: t.Role},
	}
}

// ScanDest returns a slice of pointers to User fields for database scanning.
func (t *User) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.Username,
		&t.Email,
		&t.Password,
		&t.FullName,
		&t.Avatar,
		&t.Bio,
		&t.Website,
		&t.Location,
		&t.IsActive,
		&t.Role,
	}
}

// FetchUser creates a FetchFunc for User.
func FetchUser() goent.FetchFunc {
	return func(target any) []any {
		return target.(*User).ScanDest()
	}
}

// ------------------------------
// Watch
// ------------------------------

// implement goent.Entity interface GetID for Watch
func (t *Watch) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Watch
func (t *Watch) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Watch) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "user_id", Value: t.UserID},
		{Key: "repository_id", Value: t.RepositoryID},
	}
}

// ScanDest returns a slice of pointers to Watch fields for database scanning.
func (t *Watch) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UserID,
		&t.RepositoryID,
	}
}

// FetchWatch creates a FetchFunc for Watch.
func FetchWatch() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Watch).ScanDest()
	}
}

// ------------------------------
// Webhook
// ------------------------------

// implement goent.Entity interface GetID for Webhook
func (t *Webhook) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Webhook
func (t *Webhook) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Webhook) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "created_at", Value: t.CreatedAt},
		{Key: "updated_at", Value: t.UpdatedAt},
		{Key: "repository_id", Value: t.RepositoryID},
		{Key: "url", Value: t.URL},
		{Key: "secret", Value: t.Secret},
		{Key: "is_active", Value: t.IsActive},
		{Key: "events", Value: t.Events},
	}
}

// ScanDest returns a slice of pointers to Webhook fields for database scanning.
func (t *Webhook) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CreatedAt,
		&t.UpdatedAt,
		&t.RepositoryID,
		&t.URL,
		&t.Secret,
		&t.IsActive,
		&t.Events,
	}
}

// FetchWebhook creates a FetchFunc for Webhook.
func FetchWebhook() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Webhook).ScanDest()
	}
}
